databases:
  - name: flyingclub
    databaseName: flyingclub
    user: flyingclub
    plan: free

services:
  - type: web
    name: flyingclub
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flyingclub
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false